# Site settings
title: Development Knew of andyyou
email: andyyu0920@gmail.com
description: > 
  The journals and articles are written by andyyou. Most of all just recording of how to slove problem, fix bugs in programming area.
  Apart from those I also write a bit tutorials. Here just a backup. Some content just draft or notes for me.
baseurl: "" # the subpath of your site, e.g. /blog/
encoding: utf-8
url: "http://andyyou.github.io" # the base hostname & protocol for your site
twitter_username: andyyu0920
github_username:  andyyou

# Build settings
markdown: kramdown # kramdown | redcarpet
kramdown:
  input: GFM
  syntax_highlighter: rouge
  line_numbers: false
# Default source: ./
# Default destination: ./_site